# Generated by Django 4.2 on 2023-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_alter_cliente_cpf_alter_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
    ]
