# Generated by Django 4.2 on 2023-05-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_rename_user_cliente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
    ]
